# Generated by Django 3.1.7 on 2021-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210324_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='대기중', max_length=32, verbose_name='상태'),
        ),
    ]
